# Generated by Django 2.0.5 on 2018-05-04 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('nationality', models.CharField(blank=True, choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('ALG', 'Algeria'), ('AND', 'Andorra'), ('ANG', 'Angola'), ('ANT', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('ARU', 'Aruba'), ('ASA', 'American Samoa'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaijan'), ('BAH', 'Bahamas'), ('BAN', 'Bangladesh'), ('BAR', 'Barbados'), ('BDI', 'Burundi'), ('BEL', 'Belgium'), ('BEN', 'Benin'), ('BER', 'Bermuda'), ('BHU', 'Bhutan'), ('BIH', 'Bosnia and Herzegovina'), ('BIZ', 'Belize '), ('BLR', 'Belarus'), ('BOL', 'Bolivia'), ('BOT', 'Botswana'), ('BRA', 'Brazil'), ('BRN', 'Bahrain'), ('BRU', 'Brunei'), ('BUL', 'Bulgaria'), ('BUR', 'Burkina Faso'), ('CAF', 'Central African Republic'), ('CAM', 'Cambodia'), ('CAN', 'Canada'), ('CAY', 'Cayman Islands'), ('CGO', 'Congo'), ('CHA', 'Chad'), ('CHI', 'Chile'), ('CHN', 'China'), ('CIV', 'Ivory Coast'), ('CMR', 'Cameroon'), ('COD', 'Democratic Republic of the Congo'), ('COK', 'Cook Islands'), ('COL', 'Colombia'), ('COM', 'Comoros'), ('CPV', 'Cape Verde'), ('CRC', 'Costa Rica '), ('CRO', 'Croatia'), ('CUB', 'Cuba'), ('CYP', 'Cyprus'), ('CZE', 'Czech Republic '), ('DEN', 'Denmark'), ('DJI', 'Djibouti'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('ECU', 'Ecuador'), ('EGY', 'Egypt'), ('ERI', 'Eritrea'), ('ESA', 'El Salvador'), ('ESP', 'Spain'), ('EST', 'Estonia'), ('ETH', 'Ethiopia'), ('FIJ', 'Fiji'), ('FIN', 'Finland'), ('FRA', 'France'), ('FSM', 'Federated States of Micronesia'), ('GAB', 'Gabon'), ('GAM', 'The Gambia'), ('GBR', 'Great Britain'), ('GBS', 'Guinea-Bissau'), ('GEO', 'Georgia'), ('GEQ', 'Equatorial Guinea'), ('GER', 'Germany'), ('GHA', 'Ghana'), ('GRE', 'Greece'), ('GRN', 'Grenada'), ('GUA', 'Guatemala'), ('GUI', 'Guinea'), ('GUM', 'Guam'), ('GUY', 'Guyana'), ('HAI', 'Haiti'), ('HKG', 'Hong Kong'), ('HON', 'Honduras'), ('HUN', 'Hungary'), ('INA', 'Indonesia'), ('IND', 'India'), ('IRI', 'Iran'), ('IRL', 'Ireland'), ('IRQ', 'Iraq'), ('ISL', 'Iceland'), ('ISR', 'Israel'), ('ISV', 'Virgin Islands'), ('ITA', 'Italy'), ('IVB', 'British Virgin Islands'), ('JAM', 'Jamaica'), ('JOR', 'Jordan'), ('JPN', 'Japan'), ('KAZ', 'Kazakhstan'), ('KEN', 'Kenya'), ('KGZ', ' Kyrgyzstan'), ('KIR', ' Kiribati'), ('KOR', ' South Korea'), ('KOS', 'Kosovo'), ('KSA', 'Saudi Arabia'), ('KUW', 'Kuwait'), ('LAO', 'Laos'), ('LAT', 'Latvia'), ('LBA', 'Libya'), ('LBN', 'Lebanon'), ('LBR', 'Liberia'), ('LCA', 'Saint Lucia'), ('LES', 'Lesotho'), ('LIE', 'Liechtenstein'), ('LTU', 'Lithuania'), ('LUX', 'Luxembourg'), ('MAD', 'Madagascar'), ('MAR', 'Morocco'), ('MAS', 'Malaysia'), ('MAW', 'Malawi'), ('MDA', 'Moldova'), ('MDV', 'Maldives'), ('MEX', 'Mexico'), ('MGL', 'Mongolia'), ('MHL', 'Marshall Islands'), ('MKD', 'Macedonia'), ('MLI', 'Mali'), ('MLT', 'Malta'), ('MNE', 'Montenegro'), ('MON', 'Monaco'), ('MOZ', 'Mozambique'), ('MRI', 'Mauritius'), ('MTN', 'Mauritania'), ('MYA', 'Myanmar'), ('NAM', 'Namibia'), ('NCA', 'Nicaragua'), ('NED', 'Netherlands'), ('NEP', 'Nepal'), ('NGR', 'Nigeria'), ('NIG', 'Niger'), ('NOR', 'Norway'), ('NRU', 'Nauru'), ('NZL', 'New Zealand'), ('OMA', 'Oman'), ('PAK', 'Pakistan'), ('PAN', 'Panama'), ('PAR', 'Paraguay'), ('PER', 'Peru'), ('PHI', 'Philippines'), ('PLE', 'Palestine'), ('PLW', 'Palau'), ('PNG', 'Papua New Guinea'), ('POL', 'Poland'), ('POR', 'Portugal'), ('PRK', 'North Korea'), ('PUR', 'Puerto Rico'), ('QAT', 'Qatar'), ('ROU', 'Romania'), ('RSA', 'South Africa'), ('RUS', 'Russia'), ('RWA', 'Rwanda'), ('SAM', 'Samoa'), ('SEN', 'Senegal'), ('SEY', 'Seychelles'), ('SGP', 'Singapore'), ('SKN', 'Saint Kitts and Nevis'), ('SLE', 'Sierra Leone'), ('SLO', 'Slovenia'), ('SMR', 'San Marino'), ('SOL', 'Solomon Islands'), ('SOM', 'Somalia'), ('SRB', 'Serbia'), ('SRI', 'Sri Lanka'), ('SSD', 'South Sudan'), ('STP', 'São Tomé and Príncipe'), ('SUD', 'Sudan'), ('SUI', 'Switzerland'), ('SUR', 'Suriname'), ('SVK', 'Slovakia'), ('SWE', 'Sweden'), ('SWZ', 'Swaziland'), ('SYR', 'Syria'), ('TAN', 'Tanzania'), ('TGA', 'Tonga'), ('THA', 'Thailand'), ('TJK', 'Tajikistan'), ('TKM', 'Turkmenistan'), ('TLS', 'East Timor'), ('TOG', 'Togo'), ('TPE', 'Chinese Taipei'), ('TTO', 'Trinidad and Tobago'), ('TUN', 'Tunisia'), ('TUR', 'Turkey'), ('TUV', 'Tuvalu'), ('UAE', 'United Arab Emirates'), ('UGA', 'Uganda'), ('UKR', 'Ukraine'), ('URU', 'Uruguay'), ('USA', 'United States'), ('UZB', 'Uzbekistan'), ('VAN', 'Vanuatu'), ('VEN', 'Venezuela'), ('VIE', 'Vietnam'), ('VIN', 'Saint Vincent and the Grenadines'), ('YEM', 'Yemen'), ('ZAM', 'Zambia'), ('ZIM', 'Zimbabwe')], max_length=3, null=True, verbose_name='nationality')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female')], null=True, verbose_name='gender')),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
